# NNETAR
Neural network model (NNETAR) to capture non-linear trends and forecast price picks.

```{r}
library(forecast)
RRS_ts <- ts(data_wide$RRS,frequency = 24)
# Train/Test separate 
n_train <- 18000
n_test <- 2352
ts_RRS_train <- subset(RRS_ts, end = n_train)
ts_RRS_test  <- subset(RRS_ts, start = n_train + 1)
```


```{r}
# fit model
RRS_nnetar_01 <- nnetar(ts_RRS_train)

# forecast
RRS_nnetar_fc <- forecast(RRS_nnetar_01, h = n_test)

plot(RRS_nnetar_fc)

# Accuracy
accuracy(RRS_nnetar_fc, ts_RRS_test)
```

The auto model generates m = 24, p (nonseasonal lag) = 28, and P (seasonal lag) = 1, size = 14. This size (number of layers in this network) is unnecessarily high for a simple model, which can be furthur tuned if chosen.

# TABATS
For TABATS, we are using multiseasonal time series.
```{r}
mtts_RRS <- msts(
  data_wide$RRS,
  seasonal.periods = c(24, 168)
)

n_train <- sum(data_wide$Date <= as.Date("2025-12-31"))
n_test <- sum(data_wide$Date >= as.Date("2026-01-01"))

mtts_RRS_train <- mtts_RRS[1:n_train]
mtts_RRS_test  <- mtts_RRS[(n_train + 1):length(mtts_RRS)]

# Fit TBATS model
system.time({
  RRS_tbats_01 <- tbats(mtts_RRS_train)
})

# Forecast
RRS_tbats_fc <- forecast(RRS_tbats_01, h = n_test)

# Plot forecast
plot(RRS_tbats_fc)

# Accuracy
accuracy(RRS_tbats_fc, mtts_RRS_test)
```

