Result table for model comparison

All models are explored in 02 and 03, with same names maintained here.

```{r}
# Extract test set metrics for each model

get_metrics <- function(acc) {
  c(
    RMSE = acc["Test set", "RMSE"],
    MAE  = acc["Test set", "MAE"],
    MASE = acc["Test set", "MASE"]
  )
}

# ARIMA
acc_arima <- accuracy(forecast_arima, test_data$RRS)

# ARIMA + Fourier
acc_fourier <- accuracy(forecast_fourier, test_data$RRS)

# NNETAR
acc_nnetar <- accuracy(RRS_nnetar_fc, ts_RRS_test)

# TBATS
acc_tbats <- accuracy(RRS_tbats_fc, as.numeric(mtts_RRS_test))

# Seasonal Naive (daily)
acc_snaive_d <- accuracy(RRS_snaive_fc, ts_RRS_test)

# Seasonal Naive (weekly)
acc_snaive_w <- accuracy(RRS_snaive_w_fc, ts_RRS_test_w)

# Combine into table
comparison_table <- rbind(
  ARIMA            = get_metrics(acc_arima),
  ARIMA_Fourier    = get_metrics(acc_fourier),
  NNETAR           = get_metrics(acc_nnetar),
  TBATS            = get_metrics(acc_tbats),
  SNaive_Daily     = get_metrics(acc_snaive_d),
  SNaive_Weekly    = get_metrics(acc_snaive_w)
)

# Convert to dataframe
comparison_table <- as.data.frame(comparison_table)

# Print nicely
round(comparison_table, 3)
write.csv(comparison_table, "model_comparison.csv", row.names = FALSE)

```

##Plot the result
```{r}
pdf("forecast_plot.pdf",
    width = 10, height = 6) 

time_test <- data_wide$Date[(n_train + 1):(n_train + n_test)]
plot(time_test, ts_RRS_test,
     type = "l",
     col = "black", lwd = 2,
     main = "Forecast vs Actual (Real Time)",
     xlab = "Date", ylab = "RRS")

lines(time_test, forecast_arima$mean, col = "#1f77b4", lwd = 1)
lines(time_test, forecast_fourier$mean, col = "#2ca02c", lwd = 1)
lines(time_test, RRS_tbats_fc$mean, col = "#ff7f0e", lwd = 1)
lines(time_test, RRS_snaive_fc$mean, col = "#d62728", lwd = 1, lty = 2)

legend("topright",
       legend = c("Actual", "ARIMA", "ARIMA+Fourier", "TBATS", "SNaive"),
       col = c("black", "#1f77b4", "#2ca02c", "#ff7f0e", "#d62728"),
       lwd = 2, lty = c(1,1,1,1,2),
       bty = "n")
dev.off()
```
```{r}
pdf("forecast_plot_zoomed.pdf",
    width = 10, height = 6) 
ylim_use <- c(0, quantile(ts_RRS_test, 0.99, na.rm = TRUE))

plot(time_test, ts_RRS_test,
     type = "l",
     col = "black", lwd = 2,
     ylim = ylim_use,
     main = "Forecast vs Actual (Zoomed)",
     xlab = "Date", ylab = "RRS")

lines(time_test, forecast_arima$mean,   col = "#1f77b4", lwd = 1)
lines(time_test, forecast_fourier$mean, col = "#2ca02c", lwd = 1)
lines(time_test, RRS_tbats_fc$mean,     col = "#ff7f0e", lwd = 1)
lines(time_test, RRS_snaive_fc$mean,    col = "#d62728", lwd = 1, lty = 2)

legend("topright",
       legend = c("Actual", "ARIMA", "ARIMA+Fourier", "TBATS", "SNaive"),
       col = c("black", "#1f77b4", "#2ca02c", "#ff7f0e", "#d62728"),
       lwd = 1, 
       cex = 0.8,
       lty = c(1,1,1,1,2), bty = "n")
dev.off()
```

```{r}
pdf("forecast_plot_2days.pdf",
    width = 10, height = 6) 
data_wide$Datetime <- as.POSIXct(
  paste(data_wide$Date, data_wide$hourEnding),
  format = "%Y-%m-%d %H:%M"
)
time_test <- data_wide$Datetime[(n_train + 1):(n_train + n_test)]
# Select first 48 hours (2 days)
idx <- 1:48

# Plot actual values
plot(time_test[idx], ts_RRS_test[idx],
     type = "l",
     col = "black", lwd = 2,
      ylim = c(0,5),
     main = "Hourly Forecast vs Actual (2 Days)",
     xlab = "Datetime", ylab = "RRS",
     las = 1)

# Add forecasts
lines(time_test[idx], forecast_arima$mean[idx],   col = "#1f77b4", lwd = 2)
lines(time_test[idx], forecast_fourier$mean[idx], col = "#2ca02c", lwd = 2)
lines(time_test[idx], RRS_tbats_fc$mean[idx],     col = "#ff7f0e", lwd = 2)
lines(time_test[idx], RRS_snaive_fc$mean[idx],    col = "#d62728", lwd = 2, lty = 2)

# Add legend (smaller & clean)
legend("topright",
       legend = c("Actual", "ARIMA", "ARIMA+Fourier", "TBATS", "SNaive"),
       col = c("black", "#1f77b4", "#2ca02c", "#ff7f0e", "#d62728"),
       lwd = 2, lty = c(1,1,1,1,2),
       cex = 0.7, bty = "n")
dev.off()
```



